# yaml-language-server: $schema=https://raw.githubusercontent.com/tourem/deploy-manifest-plugin/main/.deploy-manifest.schema.json

# Minimal configuration - uses 'basic' profile by default
profile: basic
